SELECT A.ID, CASE 
WHEN A.P<=0.25 THEN 'CRITICAL' 
WHEN A.P<=0.5 THEN 'HIGH' 
WHEN A.P<=0.75 THEN 'MEDIUM'
ELSE 'LOW'
END COLONY_NAME
FROM (SELECT ID, PERCENT_RANK() over (order by SIZE_OF_COLONY DESC) AS P FROM ECOLI_DATA) A
ORDER BY A.ID ASC