SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, (B.SIZE-A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA A, (SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) as SIZE FROM ECOLI_DATA GROUP BY YEAR) B
WHERE YEAR(A.DIFFERENTIATION_DATE)=B.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC